### ISSUE TITLE
scroll

### ISSUE THREAD

**Issue by kamyar75** [alikhaleghi76/flutter-datepicker#11]
سلام، برای تغییر تاریخ، در حالت وب، حتما نیازه که اسکرول بشه ، و با حرکت دادن موس روی تاریخ که معمولا توی برنامه های فلاتری ، شخص به حالت اپلیکیشن (حتی توی حالت وب) اون حالت رو اجرا میکنه و سعی میکنه با انتخاب و یا تکان دادن اونو تغییر بده درحالی که فقط با اسکرول موس میشه تغییرش داد ...
لطفا این قابلیت هم اضافه کنین
ممنون

**Comment by alikhaleghi76** [comment]
سلام 
الان تست کردم هم با اسکرول‌بار می‌شه اسکرولش کرد، هم با چرخوندن دکمه وسط موس و هم با نگه‌داشتن دکمه چپ موس و بالا و پایین کردنش. 
حالت دیگه‌ای هست که باید هندل بشه؟
