### ISSUE TITLE
endDate does not work on days

### ISSUE THREAD

**Issue by Ashkan4472** [alikhaleghi76/flutter-datepicker#12]
endDate Property does not works on days. for example in image below, i have set endDate to 1385/07/05 but day does not ends in 05
![image](https://user-images.githubusercontent.com/24212573/143868589-396180ff-4e84-42a7-9319-bfa649fdb198.png)
![image](https://user-images.githubusercontent.com/24212573/143869092-15c937ad-5b3c-4242-8c3a-7278480e8b57.png)

P.S: with fix for this, update shamsi_date package version too ;)

**Comment by alikhaleghi76** [comment]
Hi 
Package updated. Now the bug should be fixed and also shamsi_date is updated :D
You can get the latest version from [here](https://pub.dev/packages/flutter_linear_datepicker).
