### ISSUE TITLE
Flatbutton on flutter upgrade

### ISSUE THREAD

**Issue by Hesam-Taleghani** [alikhaleghi76/flutter-datepicker#20]
I think the latest version still has the flat button issue

**Comment by Hesam-Taleghani** [comment]
I think the latest version still has the flat button issue

**Comment by alikhaleghi76** [comment]
[https://github.com/alikhaleghi76/flutter-datepicker/commit/83bcc10e1c4c8154fc8605dd3def3e6106a7daa1](url)
