### ISSUE TITLE
خطا در فلاتر 3.22

### ISSUE THREAD

**Issue by mma-amini** [alikhaleghi76/flutter-datepicker#23]
سلام و وقت بخیر
در آخرین نسخه فلاتر لایبراری این خطا رو میده:
/Local/Pub/Cache/hosted/pub.dev/flutter_linear_datepicker-2.0.5/lib/number_picker.dart:185:62: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/F:/sdk/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
    defaultStyle = unselectedRowStyle ?? themeData.textTheme.bodyText2!;

لطفا بررسی کنید. ممنون

**Comment by alikhaleghi76** [comment]
سلام روز بخیر
استایل‌ها deprecate شدند. فرصت کنم آپدیتش می‌کنم به زودی.
ممنون که اطلاع دادید.

**Comment by alikhaleghi76** [comment]
Solved
