### ISSUE TITLE
Support for Null Safety

### ISSUE THREAD

**Issue by mohamadhadibi** [alikhaleghi76/flutter-datepicker#4]
With the release of Flutter 2, it would be important to migrate to null safety.

[Guide](https://dart.dev/null-safety/migration-guide)

**Comment by alikhaleghi76** [comment]
@mohamadhadibi Done!

[https://github.com/alikhaleghi76/flutter-datepicker/commit/a7444e49844c956248da07d9622a55e36c580f8b](url)
