### ISSUE TITLE
add font size for text and numbers

### ISSUE THREAD

**Issue by AliHoseinpoor** [alikhaleghi76/flutter-datepicker#5]
please add font size for year month day text and number

**Comment by alikhaleghi76** [comment]
Hi, feature added. 
please upgrade your package to version 2.0.1

` flutter_linear_datepicker: ^2.0.1`

**Comment by AliHoseinpoor** [comment]
> Hi, feature added.
> please upgrade your package to version 2.0.1
> 
> ` flutter_linear_datepicker: ^2.0.1`
> 
> use these properties:
> 
> ```
>   fontSize: 18.0,
>   labelSize: 14.0,
> ```

Thanks man 🙏🙏
