### ISSUE TITLE
Add textStyle for selectedText and unselectedText

### ISSUE THREAD

**Issue by AliHoseinpoor** [alikhaleghi76/flutter-datepicker#6]
If you can put a textStyle for the selectedText and unselectedText, it would be nice, for example, if we want to bold the selectedText, now it's not possible, but if the textStyle is added, we can personalize the full selectedText and the unselectedText.

**Comment by alikhaleghi76** [comment]
#7 , #8 
Changes applied. 
You can now use version 2.0.2. 

`flutter_linear_datepicker: ^2.0.2
`
